# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='fullDescription',
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
